jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'test/AvaloniaEdit.Tests'
    displayName: 'Run Tests'

  - task: DotNetCoreCLI@2
    displayName: 'Pack AvaloniaEdit'
    inputs:
      packagesToPack: 'src\AvaloniaEdit\AvaloniaEdit.csproj;src\AvaloniaEdit.TextMate\AvaloniaEdit.TextMate.csproj'
      command: pack
      outputDir: '$(Build.ArtifactStagingDirectory)/NuGet'
      verbosityPack: normal
      versioningScheme: byBuildNumber
      majorVersion: '11' # Required when versioningScheme == ByPrereleaseNumber
      minorVersion: '0' # Required when versioningScheme == ByPrereleaseNumber
      patchVersion: '0' # Required when versioningScheme == ByPrereleaseNumber

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/NuGet'
      artifactName: 'Nuget'
    condition: succeeded()

